image: Visual Studio 2019


build_script:
- cmd: cd hello_world_application
- cmd: cmake -H. -B_build
- cmd: cmake --build _build
- cmd: cmake --build _build --target hello_world
- cmd: _build\Debug\hello_world.exe
- cmd: echo "Testing hello_world is done"
- cmd: cd ..
- cmd: cd solver_application
- cmd: cmake -H. -B_build
- cmd: cmake --build _build
- cmd: cmake --build _build --target solver
- cmd: echo "Testing solver is done"
- cmd: cmake --build _build --target solver --config Release
- cmd: echo "Testing solver is done"
- cmd: cd _build
- cmd: cpack -G WIX

deploy:
 description: Realese description
 provider: GitHub
 Authorisation: Bearer v2.2odkykmluce0cju9b55w
 artifact: /.*\.msi/
 draft: false
 on:
  APPVEYOR_REPO_TAG: true
