language: cpp

compiler:
- gcc
- clang
addons:

apt:
 sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-precise-3.7
 packages:
  - cmake
  - cmake-data
  - clang-3.7
  - g++-7
  
script:
- cd hello_world_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build _build --target hello_world
- ./_build/hello_world
- echo "hello_world_application test is done"
- cd ..
- cd solver_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build _build --target solver
- echo "solver_application test is done"
- cmake --build _build --target package_source
- cd _build
- if [ "" = "osx" ]; then 
    cpack -G DragNDrop  ;
  fi
- if [ "" = "linux" ]; 
    then cpack -G DEB;
  fi

deploy:
 provider: releases
 api_key:
   secure:     
    MIGJAoGBAKY1mJtfyxF51Z8XSE4q/kLixEUegc4UGyP0lTH/URfJ3Yg7HzNwOXNg\nxWYtBWg8foI6H71J25iDGFYFA7ihY1GwDDlfd/RmYzBHD3nrVRdzYvvqKZgAfS9J\nvQnqfMVBRNYlP6osvgf394BvOTCrXh7WEQX6zLD0PO1wKgIEHhBzAgMBAAE=
  - solver_application/_build/solver-source-files.zip
  - solver_application/_build/solver-source-files.tar.gz
  - if [ "" = "osx" ]; then 
      'solver_application/_build/solver.dmg';
    fi
  - if [ "" = "linux" ]; then 
      'solver_application/_build/solver.rpm'; 
    fi
 skip_cleanup: 'true'
 on:
  tags: true
